### ISSUE TITLE
Bravetools fails to deploy an image on a remote if using the source image on the remote

### ISSUE THREAD

**Issue by idroz** [bravetools/bravetools#204]
Consider the following set up:

1. A remote `amd64` is added to Bravetools
2. The remote `amd64` is used to build an image (see Bravefile below)
3. The resulting image is pushed to the remote
4. `brave deploy` is run with `amd64` remote as the target for a deployed unit.

Since the image already exists on the remote, LXD raises an error:

`failed to import image: Image with same fingerprint already exists`

A possible work around is to check if the image exists on the remote and not re-import it during brave deploy.

Bravefile:

```yaml
image: amd64:python/3.10
base:
  image: alpine/edge
  location: public
packages:
  manager: apk
  system:
  - bash
  - python3
run:
- command: sh
  args:
  - -c
  - echo Hello World
service:
  name: python
  docker: "no"
  resources:
    ram: 4GB
    cpu: 2
    gpu: "no"
```
