### ISSUE TITLE
Fail to initiate bravetools inside brave unit

### ISSUE THREAD

**Issue by adrozdovbering** [bravetools/bravetools#250]
**Describe the bug**

Bravetools is running on Mac OS with Multipass backend. There's a functioning multipass instance that serves as a remote Bravetools machine. New brave unit created from Bravefile and has latest version on LXD (5.19) installed via snap. When initiating Bravetools with dir backend `brave init` inside this unit with command `brave init --config config.yml` it fails with error: "failed to create lxc storage"

**To Reproduce**
Steps to reproduce the behaviour. If you're able to do so, please also include the corresponding Bravefile.

1. Initiate Bravetools with Multipass  backend and instance name `brave` 
2. Create a new brave unit using Bravefile:

```
base:
  image: ubuntu/22.04
  location: public

packages:
  manager: apt
  system:
    - software-properties-common
    - vim
    - git
    - build-essential
    - libssl-dev
    - libffi-dev
    - libsasl2-dev
    - libldap2-dev
    - libmysqlclient-dev
    - curl
    - make
    - wget
    - sqlite3
    - libsqlite3-dev
    - snapd
    - zfsutils-linux

run:
  - command: snap
    args:
      - install
      - lxd

  - command: bash
    args:
      - -c
    content: |-
      wget https://github.com/bravetools/bravetools/releases/download/2.00/brave_linux_amd64 && \
      mv brave_linux_amd64 brave && \
      mv brave /usr/bin/ && \
      chmod +x /usr/bin/brave

service:
  image: brave-test
  name: brave-test
  version: 1.0
  ip: ""
  ports:
    - 5005:5005
  resources:
    ram: 4GB
    cpu: 2
```

3. Open terminal in `brave-test` unit

```
multipass shell brave
lxc exec brave-test
```

4. Create a `config.yml` file

```
name: brave
trust: brave
profile: brave
storage:
  type: dir
  name: brave
  size: ""
network:
  name: bravebr0
  ip: 10.30.30.1
backendsettings:
  type: lxd
  resources:
    name: ""
    os: ""
    cpu: ""
    ram: ""
    hd: ""
    ip: 0.0.0.0
status: inactive
remote: local
```

5. Initiate Bravetools

```
brave init --config config.yml
```

Bravetools fails to create `dir` storage

**Expected behavior**

Bravetools should be initiated without errors.

**Environment (please complete the following information):**
 - Your operating system name and version:

Mac OS Sonoma 14.0

 - Bravetools version:

Bravetools Version: release-2.00

 - LXD version

lxd version
5.19

lxc version
Client version: 5.19
Server version: 5.19
